export const basicLibraryInfoObject = {
  "ok": true,
  "status": 200,
  "data": {
    "result": {
      "success": true,
      "library": {
        "libraryId": 1,
        "isDefault": 1,
        "baseUrl": "https://mocklibrary.com",
        "displayName": "Mock Library",
        "homeLink": "https://mocklibrary.com",
        "languageAndDisplayInHeader": 1,
        "twitterLink": "",
        "facebookLink": "",
        "youtubeLink": "",
        "instagramLink": "",
        "pinterestLink": "",
        "goodreadsLink": "",
        "tiktokLink": "",
        "generalContactLink": "",
        "email": "",
        "themeId": 1,
        "allowLinkedAccounts": "1",
        "allowUserLists": "1",
        "showHoldButton": 1,
        "allowFreezeHolds": "1",
        "maxDaysToFreeze": 365,
        "showCardExpiration": 1,
        "showCardExpirationWarnings": 1,
        "enableReadingHistory": 1,
        "enableSavedSearches": 1,
        "allowPinReset": 0,
        "allowProfileUpdates": 1,
        "enableForgotPasswordLink": 1,
        "enableForgotBarcode": 0,
        "showShareOnX": 0,
        "showShareOnFacebook": 0,
        "showShareOnPinterest": 0,
        "showShareOnLink": 1,
        "discoveryVersion": "26.07.00",
        "usernameLabel": "Library Card Number/Username",
        "passwordLabel": "PIN/Password",
        "code": "",
        "finePaymentType": 13,
        "showAvailableCoversInSummon": 0,
        "showAlternateLibraryCard": 1,
        "enableAspenMaterialsRequest": true,
        "enableSelfRegistration": 1,
        "selfRegistrationFormMessage": "\u003cp\u003ePlease complete this form to request a new library card. Online applications receive provisional privileges; visit the library with valid identification to activate full access.\u003c/p\u003e",
        "selfRegistrationSuccessMessage": "\u003cp\u003eCongratulations! Your library card request is complete. A confirmation email may follow with additional details. Please visit the library with valid identification to finalize your account and enjoy full borrowing privileges.\u003c/p\u003e",
        "promptForBirthDateInSelfReg": 0,
        "allowRememberPickupLocation": 1,
        "allowPickupLocationUpdates": 1,
        "offerImmediateHoldFreeze": 1,
        "barcodeStyle": "CODE128",
        "quickSearches": [],
        "notifications": {
          "id": 1,
          "name": "default",
          "sendTo": 2,
          "notifySavedSearch": 1,
          "notifyCustom": 1,
          "notifyAccount": 1,
          "ilsNotificationSettingId": 1
        },
        "logo": "https://mocklibrary.com/files/original/mock_library_discovery_logo.png",
        "favicon": "https://mocklibrary.com/files/original/favicon.png",
        "headerLogoApp": "https://mocklibrary.com/files/original/header_logo_app.png",
        "headerLogoWidth": 667,
        "headerLogoHeight": 200,
        "headerLogoAlignmentApp": 1,
        "headerLogoBackgroundColorApp": "#ffffff",
        "primaryBackgroundColor": "#508738",
        "primaryForegroundColor": "#ffffff",
        "secondaryBackgroundColor": "#d8e3d2",
        "secondaryForegroundColor": "#303030",
        "tertiaryBackgroundColor": "#acc49c",
        "tertiaryForegroundColor": "#000000",
        "locations": {
          "1": {
            "id": 1,
            "displayName": "Mock Library",
            "isMainBranch": true,
            "showInLocationsAndHoursList": true
          },
        },
        "pinValidationRules": {
          "minLength": "4",
          "maxLength": 6,
          "onlyDigitsAllowed": 1,
          "requireStrongPassword": false
        },
        "forgotPasswordType": "emailResetLink",
        "ils": "koha",
        "displayIlsInbox": true,
        "supportAccountNotifications": true,
        "catalogRegistrationCapabilities": {
          "lookupAccountByEmail": true,
          "lookupAccountByPhone": true,
          "basicRegistration": true,
          "forgottenPassword": true,
          "initiatePasswordResetByEmail": true,
          "initiatePasswordResetByBarcode": true,
          "enableSelfRegistration": 1,
          "selfRegistrationUrl": "",
          "enableSelfRegistrationInApp": 1
        },
        "suspendRequiresReactivationDate": true,
        "showDateWhenSuspending": true,
        "reactivateDateNotRequired": true,
        "groupedWorkDisplaySettings": {
          "superScopeLabel": "Entire Collection",
          "localLabel": "Mock Library",
          "availableLabel": "Available Now",
          "availableOnlineLabel": "Available Online",
          "availabilityToggleValue": "global",
          "facetCountsToShow": 2
        },
        "libbyReaderName": "Libby",
        "showFines": "1",
        "generalSettings": {
          "autoRotateCard": 0
        },
        "enableSelfRegistrationInApp": 1,
        "showMoreInfoBtn": 1,
        "hasEventSettings": true,
        "hasCommunityEngagementEnabled": false,
        "palaceProjectInstructions": "\u0026lt;p\u0026gt;The Palace Project has a wide variety of eBooks and eAudioBooks for use on your mobile device. \u0026lt;/p\u0026gt;\u0026lt;p\u0026gt;Palace Project titles can be read or listened using the Palace Project app which is available for both iOS and Android devices. At this time, the Palace Project app is not available on Kindle, PC, Linux, or other devices.\u0026lt;/p\u0026gt;\u0026lt;p\u0026gt;To use the Palace Project, follow these simple steps: \u0026lt;/p\u0026gt;\u0026lt;ol\u0026gt;\u0026lt;li\u0026gt;Download the App on your device  \u0026lt;/li\u0026gt;\u0026lt;/ol\u0026gt;\u0026lt;p\u0026gt;\u0026lt;a href\u003d\u0026quot;https://apps.apple.com/us/app/the-palace-project/id1574359693#?platform\u003diphone\u0026quot;\u0026gt;\u0026lt;img src\u003d\u0026quot;/images/app_store_badge.png\u0026quot; alt\u003d\u0026quot;Download on the App Store\u0026quot; class\u003d\u0026quot;img-responsive\u0026quot; /\u0026gt;\u0026lt;/a\u0026gt;\u0026lt;/p\u0026gt;\u0026lt;p\u0026gt;\u0026lt;a href\u003d\u0026quot;https://play.google.com/store/apps/details?id\u003dorg.thepalaceproject.palace\u0026amp;amp;pli\u003d1\u0026quot;\u0026gt;\u0026lt;img src\u003d\u0026quot;/images/google-play-badge.png\u0026quot; alt\u003d\u0026quot;Get it on Google Play\u0026quot; class\u003d\u0026quot;img-responsive\u0026quot; /\u0026gt;\u0026lt;/a\u0026gt;\u0026lt;/p\u0026gt;\u0026lt;ol start\u003d\u0026quot;2\u0026quot;\u0026gt;\u0026lt;li\u0026gt;\u0026lt;p\u0026gt;Select your library\u0026lt;br /\u0026gt;After downloading the app, select \u0026ldquo;Find Your Library,\u0026rdquo; and choose your library from the alphabetized selection.\u0026lt;/p\u0026gt;\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;\u0026lt;p\u0026gt;Sign in\u0026lt;br /\u0026gt;Select the settings icon in the lower-right hand corner of the screen, then enter your LIBRARY CARD NUMBER and LIBRARY PASSWORD and select LOG IN.\u0026lt;/p\u0026gt;\u0026lt;/li\u0026gt;\u0026lt;/ol\u0026gt;\u0026lt;p\u0026gt;For more information, visit \u0026lt;a href\u003d\u0026quot;https://thepalaceproject.org/information-for-library-patrons/\u0026quot;\u0026gt;the Palace Project website\u0026lt;/a\u0026gt;. \u0026lt;/p\u0026gt;",
        "alternateLibraryCardConfig": {
          "alternateLibraryCardLabel": "",
          "alternateLibraryCardFormMessage": "",
          "alternateLibraryCardStyle": "none",
          "showAlternateLibraryCardPassword": 0,
          "alternateLibraryCardPasswordLabel": ""
        },
        "useAlternateCardForCloudLibrary": 0,
        "materialRequestType": 1,
        "displayMaterialsRequest": 1,
        "materialsRequestLinkUrl": ""
      }
    }
  },
};
