export const basicThemeObject = {
     aliases: {
          bg: "backgroundColor",
          bgColor: "backgroundColor",
          h: "height",
          m: "margin",
          mb: "marginBottom",
          ml: "marginLeft",
          mr: "marginRight",
          mt: "marginTop",
          mx: "marginHorizontal",
          my: "marginVertical",
          p: "padding",
          pb: "paddingBottom",
          pl: "paddingLeft",
          pr: "paddingRight",
          pt: "paddingTop",
          px: "paddingHorizontal",
          py: "paddingVertical",
          rounded: "borderRadius",
          w: "width"
     },
     components: {
          Accordion: { theme: [{}] },
          AccordionContent: { theme: [{}] },
          AccordionContentText: { theme: [{}] },
          AccordionHeader: { theme: [{}] },
          AccordionIcon: { theme: [{}] },
          AccordionItem: { theme: [{}] },
          AccordionTitleText: { theme: [{}] },
          AccordionTrigger: { theme: [{}] },
          Actionsheet: { theme: [{}] },
          ActionsheetBackdrop: { theme: [{}] },
          ActionsheetContent: { theme: [{}] },
          ActionsheetDragIndicator: { theme: [{}] },
          ActionsheetFlatList: { theme: [{}] },
          ActionsheetIcon: { theme: [{}] },
          ActionsheetIndicatorWrapper: { theme: [{}] },
          ActionsheetItem: { theme: [{}] },
          ActionsheetItemText: { theme: [{}] },
          ActionsheetScrollView: { theme: [{}] },
          ActionsheetSectionHeaderText: { theme: [{}] },
          ActionsheetSectionList: { theme: [{}] },
          ActionsheetVirtualizedList: { theme: [{}] },
          Alert: { theme: [{}] },
          AlertDialog: { theme: [{}] },
          AlertDialogBackdrop: { theme: [{}] },
          AlertDialogBody: { theme: [{}] },
          AlertDialogCloseButton: { theme: [{}] },
          AlertDialogContent: { theme: [{}] },
          AlertDialogFooter: { theme: [{}] },
          AlertDialogHeader: { theme: [{}] },
          AlertIcon: { theme: [{}] },
          AlertText: { theme: [{}] },
          Avatar: { theme: [{}] },
          AvatarBadge: { theme: [{}] },
          AvatarFallbackText: { theme: [{}] },
          AvatarGroup: { theme: [{}] },
          AvatarImage: { theme: [{}] },
          Badge: { theme: [{}] },
          BadgeIcon: { theme: [{}] },
          BadgeText: { theme: [{}] },
          BaseIcon: { theme: [{}] },
          Box: { theme: [{}] },
          Button: { theme: [{}] },
          ButtonGroup: { theme: [{}] },
          ButtonGroupHSpacer: { theme: [{}] },
          ButtonGroupVSpacer: { theme: [{}] },
          ButtonIcon: { theme: [{}] },
          ButtonSpinner: { theme: [{}] },
          ButtonText: { theme: [{}] },
          Card: { theme: [{}] },
          Center: { theme: [{}] },
          Checkbox: { theme: [{}] },
          CheckboxGroup: { theme: [{}] },
          CheckboxIcon: { theme: [{}] },
          CheckboxIndicator: { theme: [{}] },
          CheckboxLabel: { theme: [{}] },
          Divider: { theme: [{}] },
          Fab: { theme: [{}] },
          FabIcon: { theme: [{}] },
          FabLabel: { theme: [{}] },
          FlatList: { theme: [{}] },
          FormControl: { theme: [{}] },
          FormControlError: { theme: [{}] },
          FormControlErrorIcon: { theme: [{}] },
          FormControlErrorText: { theme: [{}] },
          FormControlHelper: { theme: [{}] },
          FormControlHelperText: { theme: [{}] },
          FormControlLabel: { theme: [{}] },
          FormControlLabelText: { theme: [{}] },
          HStack: { theme: [{}] },
          Heading: { theme: [{}] },
          Icon: { theme: [{}] },
          Image: { theme: [{}] },
          ImageBackground: { theme: [{}] },
          Input: { theme: [{}] },
          InputAccessoryView: { theme: [{}] },
          InputField: { theme: [{}] },
          InputIcon: { theme: [{}] },
          InputSlot: { theme: [{}] },
          KeyboardAvoidingView: { theme: [{}] },
          Link: { theme: [{}] },
          LinkText: { theme: [{}] },
          Menu: { theme: [{}] },
          MenuBackdrop: { theme: [{}] },
          MenuItem: { theme: [{}] },
          MenuLabel: { theme: [{}] },
          MenuSeparator: { theme: [{}] },
          Modal: { theme: [{}] },
          ModalBackdrop: { theme: [{}] },
          ModalBody: { theme: [{}] },
          ModalCloseButton: { theme: [{}] },
          ModalContent: { theme: [{}] },
          ModalFooter: { theme: [{}] },
          ModalHeader: { theme: [{}] },
          Popover: { theme: [{}] },
          PopoverArrow: { theme: [{}] },
          PopoverBackdrop: { theme: [{}] },
          PopoverBody: { theme: [{}] },
          PopoverCloseButton: { theme: [{}] },
          PopoverContent: { theme: [{}] },
          PopoverFooter: { theme: [{}] },
          PopoverHeader: { theme: [{}] },
          Pressable: { theme: [{}] },
          Progress: { theme: [{}] },
          ProgressFilledTrack: { theme: [{}] },
          Radio: { theme: [{}] },
          RadioGroup: { theme: [{}] },
          RadioIcon: { theme: [{}] },
          RadioIndicator: { theme: [{}] },
          RadioLabel: { theme: [{}] },
          RefreshControl: { theme: [{}] },
          SafeAreaView: { theme: [{}] },
          ScrollView: { theme: [{}] },
          SectionList: { theme: [{}] },
          Select: { theme: [{}] },
          SelectActionsheet: { theme: [{}] },
          SelectActionsheetBackdrop: { theme: [{}] },
          SelectActionsheetContent: { theme: [{}] },
          SelectActionsheetDragIndicator: { theme: [{}] },
          SelectActionsheetFlatList: { theme: [{}] },
          SelectActionsheetIcon: { theme: [{}] },
          SelectActionsheetIndicatorWrapper: { theme: [{}] },
          SelectActionsheetItem: { theme: [{}] },
          SelectActionsheetItemText: { theme: [{}] },
          SelectActionsheetScrollView: { theme: [{}] },
          SelectActionsheetSectionHeaderText: { theme: [{}] },
          SelectActionsheetSectionList: { theme: [{}] },
          SelectActionsheetVirtualizedList: { theme: [{}] },
          SelectIcon: { theme: [{}] },
          SelectInput: { theme: [{}] },
          SelectTrigger: { theme: [{}] },
          Slider: { theme: [{}] },
          SliderFilledTrack: { theme: [{}] },
          SliderThumb: { theme: [{}] },
          SliderThumbInteraction: { theme: [{}] },
          SliderTrack: { theme: [{}] },
          Spinner: { theme: [{}] },
          StatusBar: { theme: [{}] },
          Switch: { theme: [{}] },
          Tabs: { theme: [{}] },
          TabsTab: { theme: [{}] },
          TabsTabIcon: { theme: [{}] },
          TabsTabList: { theme: [{}] },
          TabsTabPanel: { theme: [{}] },
          TabsTabPanels: { theme: [{}] },
          TabsTabTitle: { theme: [{}] },
          Text: { theme: [{}] },
          Textarea: { theme: [{}] },
          TextareaInput: { theme: [{}] },
          Toast: { theme: [{}] },
          ToastDescription: { theme: [{}] },
          ToastTitle: { theme: [{}] },
          Tooltip: { theme: [{}] },
          TooltipContent: { theme: [{}] },
          TooltipText: { theme: [{}] },
          VStack: { theme: [{}] },
          View: { theme: [{}] },
          VirtualizedList: { theme: [{}] }
     },
     globalStyle: {
          variants: {
               hardShadow: [{}],
               softShadow: [{}]
          }
     },
     plugins: [
          {
               AnimatePresenceComp: {},
               componentDriver: {},
               config: {},
               name: "AnimationResolver"
          }
     ],
     tokens: {
          borderWidths: { "0": 0, "1": 1, "2": 2, "4": 4, "8": 8 },
          breakpoints: { base: 0, lg: 992, md: 768, sm: 480, xl: 1280 },
          colors: {
               primary: {
                    "100": "#d1e9c6", "100-text": "#000000", "200": "#b4daa4", "200-text": "#000000",
                    "300": "#97cb81", "300-text": "#000000", "400": "#7abc5e", "400-text": "#000000",
                    "50": "#ecf9e6", "50-text": "#000000", "500": "#61a244", "500-text": "#000000",
                    "600": "#4b7e34", "600-text": "#ffffff", "700": "#355a24", "700-text": "#ffffff",
                    "800": "#1e3714", "800-text": "#ffffff", "900": "#051400", "900-text": "#ffffff",
                    base: "#4b7e34", baseContrast: "#ffffff"
               },
               secondary: {
                    "100": "#d6e2d0", "100-text": "#000000", "200": "#bcceb2", "200-text": "#000000",
                    "300": "#a1ba94", "300-text": "#000000", "400": "#87a675", "400-text": "#000000",
                    "50": "#eff6eb", "50-text": "#000000", "500": "#6d8d5c", "500-text": "#000000",
                    "600": "#556d47", "600-text": "#ffffff", "700": "#3c4e33", "700-text": "#ffffff",
                    "800": "#242f1d", "800-text": "#ffffff", "900": "#091105", "900-text": "#ffffff",
                    base: "#d6e2d0", baseContrast: "#000000"
               },
               tertiary: {
                    "100": "#d5e3cc", "100-text": "#000000", "200": "#bbd0ae", "200-text": "#000000",
                    "300": "#a1bc8f", "300-text": "#000000", "400": "#87a970", "400-text": "#000000",
                    "50": "#eef7e8", "50-text": "#000000", "500": "#6e9057", "500-text": "#000000",
                    "600": "#557043", "600-text": "#ffffff", "700": "#3c502f", "700-text": "#ffffff",
                    "800": "#23301a", "800-text": "#ffffff", "900": "#071201", "900-text": "#ffffff",
                    base: "#a1bc8f", baseContrast: "#000000"
               }
          },
          fontSizes: {
               "2xl": 24, "2xs": 10, "3xl": 30, "4xl": 36, "5xl": 48, "6xl": 60,
               "7xl": 72, "8xl": 96, "9xl": 128, lg: 18, md: 16, sm: 14, xl: 20, xs: 12
          },
          fontWeights: {
               black: "900", bold: "700", extraBlack: "950", extrabold: "800",
               hairline: "100", light: "300", medium: "500", normal: "400", semibold: "600", thin: "200"
          },
          fonts: { body: undefined, heading: undefined, mono: undefined },
          letterSpacings: { "2xl": 1.6, lg: 0.2, md: 0, sm: -0.2, xl: 0.4, xs: -0.4 },
          lineHeights: {
               "2xl": 32, "2xs": 16, "3xl": 40, "4xl": 48, "5xl": 56, "6xl": 72,
               "7xl": 90, lg: 24, md: 22, sm: 20, xl: 28, xs: 18
          },
          mediaQueries: {
               base: "@media screen and (min-width: 0)",
               lg: "@media screen and (min-width: 992px)",
               md: "@media screen and (min-width: 768px)",
               sm: "@media screen and (min-width: 480px)",
               xl: "@media screen and (min-width: 1280px)",
               xs: "@media screen and (min-width: 400px)"
          },
          opacity: {
               "0": 0, "10": 0.1, "100": 1, "20": 0.2, "25": 0.25, "30": 0.3,
               "40": 0.4, "5": 0.05, "50": 0.5, "60": 0.6, "70": 0.7, "75": 0.75,
               "80": 0.8, "90": 0.9, "95": 0.95
          },
          radii: { "2xl": 16, "3xl": 24, full: 9999, lg: 8, md: 6, none: 0, sm: 4, xl: 12, xs: 2 },
          space: {
               "0": 0, "0.5": 2, "1": 4, "1.5": 6, "1/2": "50%", "1/3": "33.333%",
               "1/4": "25%", "1/5": "20%", "1/6": "16.666%", "10": 40, "11": 44,
               "12": 48, "16": 64, "2": 8, "2.5": 10, "2/3": "66.666%", "2/4": "50%",
               "2/5": "40%", "2/6": "33.333%", "20": 80, "24": 96, "3": 12, "3.5": 14,
               "3/4": "75%", "3/5": "60%", "3/6": "50%", "32": 128, "4": 16, "4.5": 18,
               "4/5": "80%", "4/6": "66.666%", "40": 160, "48": 192, "5": 20,
               "5/6": "83.333%", "56": 224, "6": 24, "64": 256, "7": 28, "72": 288,
               "8": 32, "80": 320, "9": 36, "96": 384, full: "100%", px: "1px"
          }
     }
};
